### ISSUE TITLE
Unable to find any apps in '.angular-cli.json'.

### ISSUE THREAD

**Issue by EduardoRG** [SergioVarea/Landbot-app#1]
## Problema
No puedo ejecutar ningún comando de angular.

## Descripción
Tras descargarme el proyecto (`git clone https://github.com/SergioVarea/Landbot-app.git`) he instalado la versión global de angular/cli y las dependencias npm.
Una vez ejecuto el comando `npm run build`, me aparece el error descrito en el título:
```
Unable to find any apps in '.angular-cli.json'.
```

¿Sabes de qué se puede tratar?

**Comment by SergioVarea** [comment]
Buenas,
 en lugar del comando ng build, ejecuta el comando ng serve
De todas formas, ahora estoy apunto de coger un tren. Cuando llegue a casa,
maximo mañana si persiste el problema reviso que no se me haya pasado subir
algun archivo
Saludos
Siento las molestias.

**Comment by SergioVarea** [comment]
Aunque por lo que dices,
creo que el problema es que ese fichero lo tengo en el .gitignore y por eso
no esta dicho fichero en el repositorio. Pero ahora mismo no puedo
comprobarlo.

**Comment by SergioVarea** [comment]
Buenas @EduardoRG,
Acabo de revisar el código y faltaban 4 archivos, ya los he subido.
Siento las molestias.
Saludos
